Simplify preload opitons: remove preloadCache flag and detect with UR…
geolonia/normalize-japanese-addresses pull request #146
Opened 2022-01-21 03:46 UTC by kamataryo

…L scheme only

2022-01-21 06:12 UTC, keichan34 commented
@kamataryo やっぱり、最初から全てのプリロードしてキャッシュを利用するのではなく、 unfetch しているところでラッパーみたいなのを override する形に変更しましょうか。そうするとスタートアップ時間の問題も解決できるし、API/ファイルシステムなどの分離がはっきりできるようになるので

2022-01-26 02:43 UTC, kamataryo commented
@keichan34 こちら対応しました。確認お願いできますでしょうか 🙇

2022-01-26 03:08 UTC, keichan34 requested changes
new URL で URLをパースするようにしました。
あとは細かいところ確認お願いします。。
これを見てちょっと思ったんですが、もしかしたらfetch自体を環境ごとにオーバーライドするのではなく、URL protocol handler をレジスタできるような仕組みにすれば今後他のアクセス方法でできるのかな。。。
それは今の所特に無いと思うのでこの実装は簡単でいいと思うけどね。どう思います？

2022-01-26 03:08 UTC, keichan34 commented on src/normalize.ts
> +export const __fetch: { shim: FetchLike } = {
細かいけど名前をもうちょっと汎用的にしようか。。例えば

`export const __internals = { fetch }` とか？今後他のものをこういう形でオーバーライドできるようにするとか。。

2022-01-26 03:19 UTC, kamataryo commented
@keichan34 ありがとうございます。

> URL protocol handler

確かに良さそうですね。データソースをカジュアルに差し替えてもっと色々な用途に使うようになることになれば、そうしてもいいかなと思いました。大量の住所データソースが s3 にあるような時とか。

2022-01-26 03:22 UTC, kamataryo commented on src/normalize.ts
> +export const __fetch: { shim: FetchLike } = {
こちら対応しました。ありがとうございます！
https://github.com/geolonia/normalize-japanese-addresses/pull/146/commits/4a382b62c8e3e15cd2c9a78514909e84becfcf5c

2022-01-26 04:05 UTC, keichan34 requested changes
ごめん、レビュー抜けがありました :bow:

2022-01-26 04:05 UTC, keichan34 commented on README.md
> +config.japaneseAddressesApi = 'file://path/to/japanese-addresses-master/api/ja'
あ、ごめん、ここも `file:///` に直してください :bow:
`file:/path/to/...` と `file:///path/to/...` は行けるっぽいけど `file://path/to...` だと `path` がホスト名として認識されてしまいます。。

2022-01-26 04:16 UTC, kamataryo commented on README.md
> +config.japaneseAddressesApi = 'file://path/to/japanese-addresses-master/api/ja'
あ、なるほど、file:/// が絶対パスの場合正しいですね。
https://datatracker.ietf.org/doc/html/rfc8089#section-2

対応しました。ありがとうございます 🙇

2022-01-26 04:17 UTC, keichan34 approved these changes
ありがとうございます！これで行きましょう

2022-01-26 04:18 UTC, merged