Aggregate ○○町 pattern
geolonia/normalize-japanese-addresses pull request #152
Opened 2022-01-31 04:45 UTC by kamataryo

町丁目が町で終わるパターンへの対応。「○○町」の町が省略されていたとしても正規化する。

2022-01-31 04:49 UTC, keichan34 reviewed
町ありと町なし両方ある自治体あるか、確認してもらってもいいですか（japansese-addressesのデータでいいと思います）？もしあるとしたら、この処理を除外しないといけないかもしれないね。。

2022-01-31 04:55 UTC, kamataryo commented
確認します。

それから実装について、当初正規表現で対応しようと考えたのですが、例えば `京都府京都市東山区大和大路1丁目123-456` と `京都府京都市東山区大和町123-456` が区別がつかないのでこうしました。

2022-01-31 05:05 UTC, keichan34 commented
ありがとうございます！
あー。なるほど。今は確か、townを長い順で正規表現マッチしているので、新しいtownとして配列に追加すると`大和大路一丁目`と`大和町`区別できるはずですよね？

2022-01-31 05:23 UTC, kamataryo commented
あ、はい、そうですね。town に 「○○町」に加えて「○○」を追加して正規表現を作る方法で実装しています。当初は正規表現のパターン修正だけで対応できると考えていたのですができなかったので town を増やす方法にしました。

それから、ちょっと信じ難いのですが、「○○町」と「○○」が共存しているケースがかなりあります。本当に存在するのか、 japanese-addresses でデータが重複しているのか、調べ中です。

例:
- 福島県須賀川市西川町 vs. 福島県須賀川市西川
- 茨城県古河市長谷 vs. 茨城県古河市長谷町
- 茨城県古河市原 vs. 茨城県古河市原町
- 茨城県石岡市柏原 vs. 茨城県石岡市柏原町
- 茨城県龍ヶ崎市姫宮 vs. 茨城県龍ヶ崎市姫宮町
- 茨城県龍ヶ崎市野原 vs. 茨城県龍ヶ崎市野原町
- 茨城県ひたちなか市相金 vs. 茨城県ひたちなか市相金町
- 栃木県那須塩原市豊浦 vs. 栃木県那須塩原市豊浦町

japanese-addresses のデータの組み合わせのうち、 936 ペア検出。

2022-01-31 06:27 UTC, keichan34 commented
さくっと確認したんだけどありますね。。なるほど。
両方存在するときは「町なし」の補充をやめたほうがいいですね

2022-01-31 06:29 UTC, kamataryo commented
ちなみにこういうのもありました。

- 広島県三原市幸崎久和喜
- 広島県三原市幸崎町久和喜

2022-01-31 07:14 UTC, kamataryo commented
`広島県三原市幸崎久和喜` vs. `広島県三原市幸崎町久和喜` のように間に町が入る場合は除外するように修正しました。

町丁目の組み合わせテストの結果はこちらにメモしておきました。
https://gist.github.com/kamataryo/57aa11a43fa22f943cb582a17a4fcb14

2022-02-01 01:36 UTC, keichan34 requested changes
確認お願いします

2022-02-01 01:36 UTC, keichan34 commented on test/main.test.ts
> +        test('広島県三原市幸崎町久和喜789-1234', async () => {
これはどっちか町あり・町なしのはずなのかな？

2022-02-01 01:36 UTC, keichan34 commented on src/lib/cacheRegexes.ts
> +  const townsEndWithCho = towns.filter(
`towns[i].town` の Set をこの時点で作れば毎回のtowns[i].town ループを節約できるかな？
```
townSet = new Set(towns.map(x => x.town))
tows.filter(town => townSet.has(town.town.replace('/町$/')))
```
的な感じで

2022-02-01 01:36 UTC, keichan34 commented on src/lib/cacheRegexes.ts
> +    if (targetTownName.replace(/町/g, '') === townName) {
これは `/町$/` にするか `/町/g` にするか悩ましいと思うけど、どっちかにする理由をコメントで残してもらってもいいですか？ :bow:

2022-02-01 01:42 UTC, kamataryo commented on src/lib/cacheRegexes.ts
> +    if (targetTownName.replace(/町/g, '') === townName) {
ありがとうございます。こちらで対応しました 🙇 
https://github.com/geolonia/normalize-japanese-addresses/pull/152/commits/fe93e6637d081f51cf90375a7fb139a971d8b706

2022-02-01 01:50 UTC, kamataryo commented on src/lib/cacheRegexes.ts
> +    if (targetTownName.replace(/町/g, '') === townName) {
あ、こちらもでした。町を含む町丁目の判定が直っていませんでした。
町で終わる -> 町を含む に一貫して修正しました。
https://github.com/geolonia/normalize-japanese-addresses/pull/152/commits/e982f24ebb0373f1af2331e015531edd2758bbda

2022-02-01 01:56 UTC, kamataryo commented on src/lib/cacheRegexes.ts
> +    if (targetTownName.replace(/町/g, '') === townName) {
テストで検出できていない時点で何か変な気がするのでもうちょっと確認します。

2022-02-01 03:53 UTC, kamataryo commented on src/lib/cacheRegexes.ts
> +  const townsEndWithCho = towns.filter(
確かに。ありがとうざいます。こちらで修正しました。
 https://github.com/geolonia/normalize-japanese-addresses/pull/152/commits/867e3eecf6935ea8d9055c069c3f7771765de84b

2022-02-01 03:53 UTC, kamataryo commented on src/lib/cacheRegexes.ts
> +    if (targetTownName.replace(/町/g, '') === townName) {
テストを追加しました。

それから、 十六町1丁目などの漢数字と町を含むケースで壊れることがわかりましたので、対応しました。
https://github.com/geolonia/normalize-japanese-addresses/pull/152/commits/acbc8b8447e39d951fe10a81a57e715dd59fe8f9

2022-02-01 04:01 UTC, kamataryo commented on test/main.test.ts
> +        test('広島県三原市幸崎町久和喜789-1234', async () => {
このケースですが、`幸崎久和喜` と `幸崎町久和喜` のどちらも存在します。
テストケースが適当すぎたので、番地だけ変えました。https://github.com/geolonia/normalize-japanese-addresses/pull/152/commits/545492c1e5ddbd79d069cee6bebf2f06cfd96fbe

現時点では町あり・町なしの両方で別々に正規化されるべきかと思います。
例えばこの住所では、住居表示住所の導入段階によって便宜的に住所の表記が異なっているだけのため、番地はそれぞれの町丁目で重複していないはずです。なので、将来的に番地の情報を持てるようになったときに町あり・町なしでも寄せられるようにできるといいかと思いました。

2022-02-02 00:33 UTC, keichan34 approved these changes
これで行きましょうか

2022-02-02 00:40 UTC, merged