Add base registry backend with API KEY authentication
geolonia/normalize-japanese-addresses pull request #182
Opened 2022-09-08 06:51 UTC by kamataryo

2022-09-09 04:42 UTC, keichan34 requested changes
細かいのですが確認よろしくお願いします

2022-09-09 04:42 UTC, keichan34 commented on src/normalize.ts
> +  const gaiku = ''
ここと236行のwarningの解消をお願いします

2022-09-09 09:54 UTC, kamataryo commented on src/normalize.ts
> +  const gaiku = ''
ありがとうございます、取り除きました 🙇

2022-09-11 23:32 UTC, keichan34 approved these changes
ありがとうございます！

2022-09-12 04:39 UTC, merged