x.y.z のタグがプッシュされた際にリリースを作成するActionsの作成
geolonia/normalize-japanese-addresses pull request #213
Opened 2023-06-23 12:19 UTC by RikitoNoto

初めまして！

[#212](https://github.com/geolonia/normalize-japanese-addresses/issues/212)自動リリースの作成を行うブランチを作成しました。

- [x] 名前が「x.y.z」形式のタグが生成されると実行されて、以下のステータスでリリースを作成します。
**リリース名**： タグ名と同じ(x.y.z)
**リリースノート**： 手動リリース時の「generate release notes」ボタンを押下時と同じ

貢献方法の詳細が見当たらず、プルリクエストや貢献の方法が誤っていましたらすみません。

2023-06-25 23:03 UTC, kamataryo requested changes
@RikitoNoto こんにちは！プルリクエストいただきありがとうございます！
いくつか修正をお願いしたいところがありました。
コメントさせていただきましたので、無理のない範囲でご対応いただけると助かります。

#211 の記述が曖昧でご迷惑をおかけしました。手探りでパッチを作成いただき、ありがとうございます！

2023-06-25 23:03 UTC, kamataryo commented on .github/workflows/create_release.yml
> +
リリースを作成するための権限が必要で、workflow の YAML ファイルのルートに以下の設定が必要なようでした。追加お願いできますでしょうか？

```yaml
permissions:
  contents: write
```

2023-06-26 03:46 UTC, RikitoNoto commented on .github/workflows/create_release.yml
> +      - '*.*.*'
すみません、気がついておりませんでした！
修正いたしました！

2023-06-26 03:47 UTC, RikitoNoto commented on .github/workflows/create_release.yml
> +        uses: actions/checkout@v2
すみません、古いバージョンになってました。
バージョンを変更いたしました！

2023-06-26 03:47 UTC, RikitoNoto commented on .github/workflows/create_release.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
かしこまりました！
tokenの行を削除しました！

2023-06-26 03:48 UTC, RikitoNoto commented on .github/workflows/create_release.yml
> +
ご確認ありがとうございます！
permissionを追加しました！

2023-06-26 03:48 UTC, RikitoNoto commented
@kamataryo 
ご確認ありがとうございます！
修正しましたので、お時間のある時にまたご確認をお願いします！

2023-06-26 07:29 UTC, kamataryo approved these changes
ありがとうございます、マージさせていただきます！
@RikitoNoto さんのおかげでリリースのフローの自動化が進み、ユーザーの皆さんにライブラリをより適切に届けられるようになりました 🙇 

プルリクエストの貢献方法などのドキュメンテーションも充実させていきたいと思いますので、今後とも normalize-japanese-addresses をよろしくお願いいたします！

2023-06-26 07:30 UTC, merged