旧漢字・異体字リストをオブジェクトで管理する
geolonia/normalize-japanese-addresses pull request #236
Opened 2024-04-19 11:02 UTC by yuuta040208

### 概要

https://github.com/geolonia/normalize-japanese-addresses/issues/199 のIssueの一部に対応してみました🙋

> 旧漢字・異体字リストのリファクタリング。今は split した後の配列のインデックスをキーに新旧を突き合わせているが、オブジェクトなどを使うことで管理を容易にし、簡単に追加できるようにしたい。

### 方針

- 配列に追加するだけで辞書を拡張可能にする
    ```
    export const dictionary = [
      jisDai2Dictionary,
      // Add more dictionary here
      // exmapleDictionary,
    ].flat()
    ```

- 辞書は `JSON.stringify()` 可能な形式にすることで、外部からJSONファイル等をインポートするときに容易に対応可能にする
    ```
    [
      ...,
      { src: '籠', dst: '篭' },
      { src: '彌', dst: '弥' },
      { src: '麩', dst: '麸' },
    ]
    ```

2024-04-30 12:07 UTC, yuuta040208 commented
@kamataryo

お忙しいところ恐縮ですが、こちらレビューお願いいたします...🙇

2024-06-23 02:52 UTC, kamataryo commented
@yuuta040208 こんにちは。ご連絡いただきありがとうございます。また、長い間反応できずにおり申し訳ありません。
私は現在 Geolonia のメンバーではないため、このリポジトリに関する以降のご連絡につきましては @keichan34 などにお願いできればと思います。

2024-06-26 06:56 UTC, keichan34 requested changes
ありがとうございました！！素晴らしいです。
お手数をかけしますが、テストも追加をお願いいたします。
全ての旧字体じゃなくてもいいのですが、2-3個選んでちゃんと思った通りに動いてるかを確認してください。

2024-07-02 01:44 UTC, keichan34 approved these changes
ありがとうございました！

2024-07-02 01:44 UTC, merged