Fixed #94, #95
geolonia/normalize-japanese-addresses pull request #96
Opened 2021-05-08 10:53 UTC by miya0001

Fixed #94, #95

2021-05-08 16:31 UTC, miya0001 commented
* `沖縄県那覇市小禄１丁目５番２３号１丁目マンション` のように建物名があって、さらにその一文字目が数字で始まっている場合に、スペースを挿入するようにした。
* 小字があって（地番住所であり、さらにaddrに地名が入るケース）、その小字に漢数字が含まれる場合に、`patchAddr()` で正しい表記に変換するようにした。（これは [japanese-addresses](https://github.com/geolonia/japanese-addresses) で対処するほうが美しいと思う）

2021-05-09 03:28 UTC, keichan34 requested changes

2021-05-09 03:28 UTC, keichan34 commented on src/lib/patchAddr.ts
> +    pattern: '^字?家6',
`patchAddr` 関数が実行するたびに `new RegExp` よりここで RegExp を作る事によって悪影響はないのかな？

```javascript
{
    pref: '香川県',
    city: '仲多度郡まんのう町',
    town: '勝浦',
    pattern: new RegExp('^字?家6'),
}
```

2021-05-09 05:10 UTC, miya0001 commented on src/lib/patchAddr.ts
> +    pattern: '^字?家6',
この場合、都道府県名、市区町村名、町名の3つがマッチした住所にだけ正規表現をコンパイルするようにしたほうが、わずかながらエコになると思うんですよね。

2021-05-10 00:25 UTC, keichan34 commented on src/lib/patchAddr.ts
> +    pattern: '^字?家6',
テストが問題なさそうでしたのでコミットしました

このリストが長くなると

```
patches = {
  "香川県": {
    "仲多度郡まんのう町": {
      "勝浦": [ { pattern: new RegExp('^字?家6'), result: "家六" } ]
```

にした方がパーフォーマンス的には良くなるけど、今は特に大きい差は無いのでおそらく問題ないと思います :bow:

2021-05-10 00:26 UTC, keichan34 approved these changes

2021-05-10 01:01 UTC, miya0001 commented on src/lib/patchAddr.ts
> +    pattern: '^字?家6',
最終的には以下で吸収したいですね。
https://github.com/geolonia/japanese-addresses/issues/36

2021-05-10 01:02 UTC, merged